[package]
name = "ckb-always-success-script"
version = "0.0.1"
edition = "2018"
license = "MIT"
description = "CKB always success script"
repository = "https://github.com/jjyr/ckb-always-success-script"
include = ["src/lib.rs", "specs"]
authors = ["JJy"]

[dependencies]
